export const MBService = {
    getMBData() {
        return [
            {
                id: '1',
                title: 'Car',
                gender: 'Male',
                age: '18-30',          
                quantity: 16,
                winConfiguration: 'every 18 person',
            },
            {
                id: '2',
                title: 'Book',
                gender: 'Female',
                age: '25-40',          
                quantity: 25,
                winConfiguration: 'every 20 person',
            },
            {
                id: '3',
                title: 'Phone',
                gender: 'Male',
                age: '18-30',          
                quantity: 20,
                winConfiguration: 'every 15 person',
            },
            {
                id: '4',
                title: 'Laptop',
                gender: 'Female',
                age: '30-45',          
                quantity: 10,
                winConfiguration: 'every 25 person',
            },
            {
                id: '5',
                title: 'Watch',
                gender: 'Male',
                age: '18-30',          
                quantity: 30,
                winConfiguration: 'every 12 person',
            },
            {
                id: '6',
                title: 'Headphones',
                gender: 'Female',
                age: '25-40',          
                quantity: 18,
                winConfiguration: 'every 22 person',
            },
            {
                id: '7',
                title: 'Guitar',
                gender: 'Male',
                age: '18-30',          
                quantity: 15,
                winConfiguration: 'every 20 person',
            },
            {
                id: '8',
                title: 'Camera',
                gender: 'Female',
                age: '30-45',          
                quantity: 12,
                winConfiguration: 'every 30 person',
            },
            {
                id: '9',
                title: 'Bike',
                gender: 'Male',
                age: '18-30',          
                quantity: 20,
                winConfiguration: 'every 15 person',
            },
            {
                id: '10',
                title: 'Tablet',
                gender: 'Female',
                age: '25-40',          
                quantity: 14,
                winConfiguration: 'every 18 person',
            },
            {
                id: '11',
                title: 'Chair',
                gender: 'Male',
                age: '18-30',          
                quantity: 25,
                winConfiguration: 'every 10 person',
            },
            {
                id: '12',
                title: 'Sunglasses',
                gender: 'Female',
                age: '30-45',          
                quantity: 8,
                winConfiguration: 'every 35 person',
            },
            {
                id: '13',
                title: 'Backpack',
                gender: 'Male',
                age: '18-30',          
                quantity: 22,
                winConfiguration: 'every 14 person',
            },
            {
                id: '14',
                title: 'Perfume',
                gender: 'Female',
                age: '25-40',          
                quantity: 20,
                winConfiguration: 'every 20 person',
            },
            {
                id: '15',
                title: 'Sneakers',
                gender: 'Male',
                age: '18-30',          
                quantity: 28,
                winConfiguration: 'every 11 person',
            },
            {
                id: '16',
                title: 'Necklace',
                gender: 'Female',
                age: '30-45',          
                quantity: 11,
                winConfiguration: 'every 28 person',
            },
            {
                id: '17',
                title: 'Watch',
                gender: 'Male',
                age: '18-30',          
                quantity: 20,
                winConfiguration: 'every 15 person',
            },
            {
                id: '18',
                title: 'Laptop Bag',
                gender: 'Female',
                age: '25-40',          
                quantity: 16,
                winConfiguration: 'every 19 person',
            },
            {
                id: '19',
                title: 'Wallet',
                gender: 'Male',
                age: '18-30',          
                quantity: 18,
                winConfiguration: 'every 17 person',
            },
            {
                id: '20',
                title: 'Hat',
                gender: 'Female',
                age: '30-45',          
                quantity: 9,
                winConfiguration: 'every 32 person',
            },
            {
                id: '21',
                title: 'Jacket',
                gender: 'Male',
                age: '18-30',          
                quantity: 24,
                winConfiguration: 'every 13 person',
            },
            {
                id: '22',
                title: 'Scarf',
                gender: 'Female',
                age: '25-40',          
                quantity: 15,
                winConfiguration: 'every 21 person',
            },
            {
                id: '23',
                title: 'T-shirt',
                gender: 'Male',
                age: '18-30',          
                quantity: 30,
                winConfiguration: 'every 9 person',
            },
            {
                id: '24',
                title: 'Jeans',
                gender: 'Female',
                age: '30-45',          
                quantity: 7,
                winConfiguration: 'every 40 person',
            },
            {
                id: '25',
                title: 'Shoes',
                gender: 'Male',
                age: '18-30',          
                quantity: 25,
                winConfiguration: 'every 16 person',
            },
            {
                id: '26',
                title: 'Dress',
                gender: 'Female',
                age: '25-40',          
                quantity: 20,
                winConfiguration: 'every 20 person',
            },
            {
                id: '27',
                title: 'Backpack',
                gender: 'Male',
                age: '18-30',          
                quantity: 20,
                winConfiguration: 'every 15 person',
            },
            {
                id: '28',
                title: 'Watch',
                gender: 'Female',
                age: '30-45',          
                quantity: 10,
                winConfiguration: 'every 30 person',
            }     
                
        ];
    },
    getMBMini() {
        return Promise.resolve(this.getMBData().slice(0, 5));
    },

    getMBSmall() {
        return Promise.resolve(this.getMBData().slice(0, 10));
    },

    getMB() {
        return Promise.resolve(this.getMBData());
    }

};

